# Copyright 2016 Markus W Mahlberg <markus.mahlberg@me.com>
#
# This file is part of cayleybench.
#
# cayleybench is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cayleybench is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with cayleybench.  If not, see <http://www.gnu.org/licenses/>.

version: '2'
services:
  benchmark:
    container_name: benchrunner
    image: mwmahlberg/cayleybench
    depends_on:
      - "postgres"
      - "mongodb"
  postgres:
    image: postgres
    logging:
      driver: none
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:3.2
    logging:
      driver: none
    ports:
      - "27017:27017"
